import os
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

def generate_company_proposal_pdf(company_name: str, output_path: str) -> str:
    """
    Generates a basic proposal PDF for the given company using reportlab.
    """
    doc = SimpleDocTemplate(output_path, pagesize=letter,
                            rightMargin=72, leftMargin=72,
                            topMargin=72, bottomMargin=18)
    
    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = ParagraphStyle(
        name='TitleStyle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#06142E'),
        spaceAfter=30
    )
    
    heading_style = ParagraphStyle(
        name='HeadingStyle',
        parent=styles['Heading2'],
        fontSize=18,
        textColor=colors.HexColor('#F5B700'),
        spaceAfter=12
    )
    
    body_style = styles['Normal']
    body_style.fontSize = 12
    body_style.leading = 14
    
    Story = []
    
    # Title
    Story.append(Paragraph(f"AI Sales Proposal: {company_name}", title_style))
    
    # Intro
    Story.append(Paragraph("Executive Summary", heading_style))
    Story.append(Paragraph(
        f"This automated proposal has been generated by the SalesIntel AI Copilot specifically for {company_name}. "
        "Our analysis indicates significant opportunities to streamline operations and leverage AI-driven workflows "
        "to drive revenue growth and reduce overhead costs.",
        body_style
    ))
    Story.append(Spacer(1, 20))
    
    # Proposed Solutions
    Story.append(Paragraph("Proposed Solutions", heading_style))
    Story.append(Paragraph(
        "Based on our intelligence dossier, we recommend the following strategic deployments:",
        body_style
    ))
    Story.append(Spacer(1, 10))
    
    points = [
        "1. Enterprise-grade AI Copilots customized for your sales force.",
        "2. Predictive analytics engines integrated directly into your CRM.",
        "3. Real-time RAG (Retrieval-Augmented Generation) document search.",
        "4. Automated compliance and reporting pipelines."
    ]
    
    for point in points:
        Story.append(Paragraph(point, body_style))
        Story.append(Spacer(1, 5))
        
    Story.append(Spacer(1, 20))
    
    # Next Steps
    Story.append(Paragraph("Next Steps & Investment", heading_style))
    Story.append(Paragraph(
        "To move forward, we propose a 30-day proof of concept (POC) focusing on your highest priority pain point. "
        "Please review the attached terms and reach out to your Account Executive to schedule the kickoff call.",
        body_style
    ))
    
    doc.build(Story)
    return output_path
